version: 2.0

jobs:
  build:
    docker:
      - image: magecloudkit/circleci-php:7.0-cli-node-browsers

    working_directory: ~/magecloudkit

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # install composer dependencies
      - run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar global config http-basic.repo.magento.com $MAGENTO_PUBLIC_KEY $MAGENTO_PRIVATE_KEY
          php composer.phar install --ignore-platform-reqs

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # compile code and generate static view files
      - run: |
          php bin/magento setup:di:compile
          php bin/magento setup:static-content:deploy -f

      # run any unit tests here if you desire
      #- run: phpunit

      # build docker images
      - run: |
          docker info
          git rev-parse HEAD > REVISION.txt
          docker info
          # ECR - use the CircleCI Build ID
          #docker build --rm=false -t magecloudkit/magento2:${CIRCLE_BUILD_NUM} .
          # Docker Hub: always tag and push latest
          docker build --rm=false -t magecloudkit/magento2:latest .

      # install aws cli tools
      - run: |
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

      # In our example we'll push to our Docker Hub account so the image is available publicly.
      # You should remove this step when configuring our own repository.
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push magecloudkit/magento2:latest

      # !!! IMPORTANT !!! - Configure your AWS credentials first. Then uncomment the code below if you
      # wish to push to an Amazon ECR repository.
      #
      # push image
      #- run: |
      #    aws ecr get-login --no-include-email --region us-east-1 | sh
      #    docker tag magecloudkit/magento2:${CIRCLE_BUILD_NUM} ${AWS_ECR_URL}/magecloudkit/magento2:${CIRCLE_BUILD_NUM}
      #    docker push ${AWS_ECR_URL}/magecloudkit/magento2:${CIRCLE_BUILD_NUM}
